### ISSUE TITLE
conversion de numeros

### ISSUE THREAD

**Issue by mae18-25** [SistemasTecTlaxiaco/actividad-2-ejercicios-equipo-maetzy-quetzaly-angel-jesus#1]
[conversion de numeros.pdf](https://github.com/user-attachments/files/16841996/conversion.de.numeros.pdf)

**Comment by Eddi3mendoz** [comment]
Portada: 24
Procedimiento: 23
Figuras, ilustraciones, fotografías: 25
Resultados y conclusiones: 24
Calificación de la práctica: 19.2

**Comment by josealfredo79** [comment]
bien hecho y revisado...
