### ISSUE TITLE
practica de conjuntos

### ISSUE THREAD

**Issue by mae18-25** [SistemasTecTlaxiaco/actividad-2-ejercicios-equipo-maetzy-quetzaly-angel-jesus#2]
[conjuntos y subconjuntos.docx](https://github.com/user-attachments/files/17141886/conjuntos.y.subconjuntos.docx)

**Comment by Proyect-A16** [comment]
Portada 25/25
Procedimiento 24/25
Figuras, ilustraciones y fotografías. 24/25
Resultados y conclusiones 25/25
Calificación: 19.6/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
