### ISSUE TITLE
practica 3

### ISSUE THREAD

**Issue by mae18-25** [SistemasTecTlaxiaco/actividad-2-ejercicios-equipo-maetzy-quetzaly-angel-jesus#3]
[proyecto 3.pdf](https://github.com/user-attachments/files/17170467/proyecto.3.pdf)

**Comment by Proyect-A16** [comment]
Portada 25/25
Procedimiento 25/25
Figuras, ilustraciones y fotografías. 25/25
Resultados y conclusiones 25/25
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
